---
title: "College Town Natural Experiments"
author: "The Mary Janes"
date: "May, 2017"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(readr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyr)
library(splines)
library(knitr)
 


# commented out code below is what is used to generate the dataframes used
# 
# retail <- readr::read_csv("../data/Dec2016/biotrackthc_dispensing.csv")
# retail$saledate <- as.Date(as.POSIXct(retail$sessiontime, origin = "1970-01-01", tz="America/Los_Angeles"))
# 
# locations <- readr::read_csv("../data/Dec2016/biotrackthc_locations.csv")
# inv.types <- readr::read_csv("../data/Dec2016/cleaned/inventory_type.csv")
# # in order to get product names to classify inhalants
# inventory <- readr::read_csv("../data/Dec2016/biotrackthc_inventory.csv")
# 
# retail.select <- retail %>%
#   # one and a half school years
#   #dplyr::filter(saledate >= "2015-09-01") %>%
#   # going back to get two summers
#    dplyr::filter(saledate >= "2015-05-15") %>%
#   # get cities for retail locations
#   dplyr::left_join(select(locations, id, city), by=c("location" = "id")) %>%
#               # college town variable
#   dplyr::mutate(collegetown = city %in% c("PULLMAN" ,"BELLEVUE","BELLINGHAM", "ELLENSBURG", "LYNNWOOD",
#                                               "EVERETT", "AUBURN", "BREMERTON", "LAKEWOOD", "DES MOINES",
#                                               "PASCO", "SHORELINE", "WALLA WALLA", "MOUNT VERNON", "RENTON",
#                                               "YAKIMA", "CENTRALIA", "KIRKLAND", "BOTHELL", "PUYALLUP",
#                                               "WENATCHEE", "LONGVIEW", "PORT ANGELES", "ABERDEEN",
#                                               "MOSES LAKE"),
#                 # big city variable
#                 bigcity = city %in% c("SEATTLE", "SPOKANE", "TACOMA", "VANCOUVER", "BELLEVUE", "EVERETT",
#                                       "YAKIMA", "RENTON"),
#                 towntype = ifelse(city == "PULLMAN", "Pullman",
#                                   ifelse(city == "ELLENSBURG", "Ellensburg",
#                                          ifelse(city == "AIRWAY HEIGHTS", "Airway Heights",
#                                                 ifelse(bigcity, "Urban",
#                                                        "NCNU")))),
#                 # incorporate sales tax
#                 price_x = ifelse(saledate >= "2015-07-01", price*1.37, price)) %>%
#   # bring in inventory type names
#   dplyr::left_join(inv.types, by="inventorytype") %>%
#   dplyr::select(retail_id = id, transactionid, location, city, collegetown, bigcity, towntype,
#                 price_x, saledate, inv_type_name, inventoryid) %>%
#   dplyr::left_join(select(inventory, id, productname), by=c("inventoryid" = "id"))
# 
# 
# retail.select <- retail.select %>%
#   dplyr::mutate(towntype = factor(towntype, levels = c("Urban", "NCNU", "Pullman", "Ellensburg", "Airway Heights")))

# 
# 
# daily_aggregate <- retail.select %>%
#   dplyr::group_by(city, saledate) %>%
#   dplyr::filter(saledate < "2017-01-01") %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc.usable = sum(inv_type_name == "Usable Marijuana") / tot_items,
#     perc.edible = sum(inv_type_name == "Liquid Marijuana Infused Edible" |
#                                      inv_type_name=="Solid Marijuana Infused Edible") / tot_items,
#     perc.extracts = sum(inv_type_name=="Marijuana Extract for Inhalation") / tot_items,
#     # keep values for collegetown
#     collegetown = collegetown[1],
#     bigcity = bigcity[1]
#   ) %>%
#   filter(revenue >= 0)
# 
# daily_aggregate_bycollegeBoolean <- retail.select %>%
#   dplyr::group_by(collegetown, saledate) %>%
#   dplyr::filter(saledate < "2017-01-01") %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc.usable = sum(inv_type_name == "Usable Marijuana") / tot_items,
#     perc.edible = sum(inv_type_name == "Liquid Marijuana Infused Edible" |
#                                      inv_type_name=="Solid Marijuana Infused Edible") / tot_items,
#     perc.extracts = sum(inv_type_name=="Marijuana Extract for Inhalation") / tot_items
#   ) %>%
#   filter(revenue >= 0)
# 
# daily_aggregate_byTownType <- retail.select %>%
#   dplyr::mutate(towntype_Pullman = ifelse(city=="PULLMAN", "Pullman", towntype)) %>%
#   dplyr::group_by(towntype_Pullman, saledate) %>%
#   dplyr::filter(saledate < "2017-01-01") %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc.usable = sum(inv_type_name == "Usable Marijuana") / tot_items,
#     perc.edible = sum(inv_type_name == "Liquid Marijuana Infused Edible" |
#                                      inv_type_name=="Solid Marijuana Infused Edible") / tot_items,
#     perc.extracts = sum(inv_type_name=="Marijuana Extract for Inhalation") / tot_items
#   ) %>%
#   filter(revenue >= 0)
# 
# 
# # get categorization functions
# source("categorization_function.R")
# inhalnames <- as.data.frame(unique(retail.select$productname[retail.select$inv_type_name=="Marijuana Extract for Inhalation"]))
# colnames(inhalnames) <- "productname"
# inhalnames$inhal_types <- as.factor(sapply(as.character(inhalnames$productname), categorizeNames))
# inhalnames$inhal_groups <- as.factor(sapply(as.character(inhalnames$inhal_types), groupProductTypesOilSep))
# retail.select$productname <- as.factor(retail.select$productname)
# retail.select <- left_join(retail.select, inhalnames, by="productname")
# 
# 
# daily_aggregate_inhaltypes_byTownType <- retail.select %>%
#   dplyr::filter(inv_type_name=="Marijuana Extract for Inhalation") %>%
#   dplyr::mutate(towntype_Pullman = ifelse(city=="PULLMAN", "Pullman", towntype)) %>%
#   dplyr::group_by(towntype_Pullman, saledate) %>%
#   dplyr::filter(saledate < "2017-01-01") %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc.cart = sum(inhal_groups == "Cartridge", na.rm = T) / tot_items,
#     perc.oil = sum(inhal_groups == "Oil", na.rm = T) / tot_items,
#     perc.hash_kief = sum(inhal_groups == "Hash/Kief", na.rm = T) / tot_items,
#     perc.wax_shatter_resin = sum(inhal_groups == "Wax/Shatter/Resin", na.rm = T) / tot_items,
#     perc.uncategorized = sum(inhal_groups == "Uncategorized", na.rm = T) / tot_items
#   ) %>%
#   filter(revenue >= 0)
# 
# daily_aggregate_PullmanUrbanRestofState <- retail.select %>%
#   dplyr::mutate(product_group = ifelse(inv_type_name=="Usable Marijuana", "Usable",
#                                        ifelse(inv_type_name=="Marijuana Extract for Inhalation", "Extracts",
#                                               ifelse(inv_type_name=="Liquid Marijuana Infused Edible" |
#                                                        inv_type_name=="Solid Marijuana Infused Edible", "Edibles",
#                                                      "Other")))) %>%
#   dplyr::group_by(towntype, saledate) %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc_usable = sum(product_group=="Usable", na.rm = T) / tot_items,
#     perc_extract = sum(product_group == "Extracts", na.rm = T) / tot_items,
#     perc_edible = sum(product_group == "Edibles", na.rm = T) / tot_items,
#     perc_other= sum(product_group == "Other", na.rm = T) / tot_items
#   ) %>%
#   dplyr::filter(revenue >= 0) %>%
#   dplyr::arrange(saledate, towntype)
# 
# pullmanUrbanRestofState_inhalants <- retail.select %>%
#   dplyr::filter(inv_type_name=="Marijuana Extract for Inhalation") %>%
#   dplyr::group_by(towntype, saledate) %>%
#   dplyr::summarise(
#     tot_items = length(retail_id),
#     perc_cartridge = sum(inhal_groups=="Cartridge", na.rm = T) / tot_items,
#     perc_oil = sum(inhal_groups=="Oil", na.rm = T) / tot_items,
#     perc_hash_kief = sum(inhal_groups == "Hash/Kief", na.rm = T) / tot_items,
#     perc_wax_shatter_resin = sum(inhal_groups == "Wax/Shatter/Resin", na.rm = T) / tot_items,
#     perc_uncategorized= sum(inhal_groups == "Uncategorized", na.rm = T) / tot_items
#   )
# 
# daily_aggregate_PullmanNoncollege <- retail.select %>%
#   dplyr::filter(!collegetown | city=="PULLMAN") %>%
#   dplyr::group_by(collegetown, saledate) %>%
#   dplyr::filter(saledate < "2017-01-01") %>%
#   dplyr::summarise(
#     revenue = sum(price_x, na.rm = T),
#     tot_items = length(retail_id),
#     avg_price_peritem = revenue / tot_items,
#     perc.usable = sum(inv_type_name == "Usable Marijuana") / tot_items,
#     perc.edible = sum(inv_type_name == "Liquid Marijuana Infused Edible" |
#                                      inv_type_name=="Solid Marijuana Infused Edible") / tot_items,
#     perc.extracts = sum(inv_type_name=="Marijuana Extract for Inhalation") / tot_items
#   ) %>%
#   filter(revenue >= 0)
# 
# 
# # write out
# write.table(daily_aggregate, file="college_towns_v3/daily_aggregate.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(daily_aggregate_bycollegeBoolean,
#             file="college_towns_v3/daily_aggregate_bycollegeBoolean.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(daily_aggregate_byTownType,
#             file="college_towns_v3/daily_aggregate_byTownType.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(daily_aggregate_inhaltypes_byTownType,
#             file="college_towns_v3/daily_aggregate_inhaltypes_byTownType.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(daily_aggregate_PullmanUrbanRestofState,
#             file="college_towns_v3/daily_aggregate_PullmanUrbanRestofState.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(pullmanUrbanRestofState_inhalants,
#             file="college_towns_v3/pullmanUrbanRestofState_inhalants.csv",
#             row.names=F, col.names=T, sep=",")
# write.table(daily_aggregate_PullmanNoncollege, file="college_towns_v3/daily_aggregate_PullmanNoncollege.csv",
#             row.names=F, col.names=T, sep=",")







# dfs for this analysis
daily_aggregate <- readr::read_csv("college_towns_v3/daily_aggregate.csv")

daily_agg_summary <- daily_aggregate %>%
  group_by(saledate) %>%
  summarise(revenue = median(revenue, na.rm=T),
            tot_items = median(tot_items, na.rm=T),
            avg_price_peritem = median(avg_price_peritem, na.rm=T),
            perc.usable = median(perc.usable, na.rm=T),
            perc.edible = median(perc.edible, na.rm=T),
            perc.extracts = median(perc.extracts, na.rm=T),
            city = "State_Avg")

daily_aggregate_bycollegeBoolean <- readr::read_csv("college_towns_v3/daily_aggregate_bycollegeBoolean.csv")

daily_aggregate_PullmanNoncollege <- readr::read_csv("college_towns_v3/daily_aggregate_PullmanNoncollege.csv")

daily_aggregate_byTownType <- readr::read_csv("college_towns_v3/daily_aggregate_byTownType.csv")

daily_aggregate_inhaltypes_byTownType <- readr::read_csv("college_towns_v3/daily_aggregate_inhaltypes_byTownType.csv")

daily_aggregate_PullmanUrbanRestofState <- readr::read_csv("college_towns_v3/daily_aggregate_PullmanUrbanRestofState.csv")

pullmanUrbanRestofState_inhalants <- readr::read_csv("college_towns_v3/pullmanUrbanRestofState_inhalants.csv")

```


### Pullman NCNU Items by Product Type, Straight Lines

```{r pullman_ncnu_items_straightlines}


daily_agg_Pullman_NCNU <- daily_aggregate_PullmanUrbanRestofState %>%
  filter(towntype=="Pullman" | towntype=="NCNU") %>%
  rename(Usable = perc_usable,
         Edibles = perc_edible,
         Extracts = perc_extract,
         Other = perc_other)

items_usable <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-01-01" & saledate <= "2016-05-06"),
              mapping = aes(x=saledate, y=Usable*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#1b9e77") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-05-06" & saledate <= "2016-08-22"),
              mapping = aes(x=saledate, y=Usable*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#1b9e77") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-08-22" & saledate < "2017-01-01"),
              mapping = aes(x=saledate, y=Usable*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#1b9e77") +
  facet_wrap("towntype", ncol=1, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="Usable", x= 'Sale Date', y = "Count of Item-Entries")


items_edibles <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-01-01" & saledate <= "2016-05-06"),
              mapping = aes(x=saledate, y=Edibles*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#d95f02") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-05-06" & saledate <= "2016-08-22"),
              mapping = aes(x=saledate, y=Edibles*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#d95f02") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-08-22" & saledate < "2017-01-01"),
              mapping = aes(x=saledate, y=Edibles*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#d95f02") +
  facet_wrap("towntype", ncol=1, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="Edibles", x= 'Sale Date', y = "")

items_extracts <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-01-01" & saledate <= "2016-05-06"),
              mapping = aes(x=saledate, y=Extracts*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#7570b3") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-05-06" & saledate <= "2016-08-22"),
              mapping = aes(x=saledate, y=Extracts*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#7570b3") +
  geom_smooth(data=subset(daily_agg_Pullman_NCNU, saledate >= "2016-08-22" & saledate < "2017-01-01"),
              mapping = aes(x=saledate, y=Extracts*tot_items),
              method = 'lm', formula = y~ns(x, df=1), color="#7570b3") +
  facet_wrap("towntype", ncol=1, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="Extracts", x= 'Sale Date', y = "")


grid.arrange(items_usable, items_edibles, items_extracts, ncol=3)


```



### Pullman, Other College Towns, 2 DF


```{r pullman_othercolleges_facet}
daily_agg_Pullman_othercollege <- daily_aggregate_PullmanUrbanRestofState %>%
  dplyr::filter(towntype!="Urban", !is.na(towntype)) %>%
  dplyr::rename(Usable = perc_usable, Extracts = perc_extract, Edibles = perc_edible, Other = perc_other) %>%
  tidyr::gather(prod_type, perc_sold, 6:9)


items_usable <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" & 
                            prod_type=="Usable"),
              mapping = aes(x=saledate, y=perc_sold*tot_items),
              method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-05-06" & saledate <= "2016-08-22" & 
                            prod_type=="Usable"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-08-22" & saledate < "2017-01-01" & 
                            prod_type=="Usable"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
  facet_grid(towntype~prod_type, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="", x= 'Sale Date', y = "Count of Item-Entries")


items_edibles <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" & 
                            prod_type=="Edibles"),
              mapping = aes(x=saledate, y=perc_sold*tot_items),
              method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-05-06" & saledate <= "2016-08-22" & 
                            prod_type=="Edibles"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-08-22" & saledate < "2017-01-01" & 
                            prod_type=="Edibles"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
  facet_grid(towntype~prod_type, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="", x= 'Sale Date', y = "")

items_extracts <- ggplot() +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" & 
                            prod_type=="Extracts"),
              mapping = aes(x=saledate, y=perc_sold*tot_items),
              method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-05-06" & saledate <= "2016-08-22" & 
                            prod_type=="Extracts"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
  geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-08-22" & saledate < "2017-01-01" & 
                            prod_type=="Extracts"),
              mapping = aes(x=saledate, y=perc_sold*tot_items), 
              method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
  facet_grid(towntype~prod_type, scales="free") +
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="", x= 'Sale Date', y = "")

grid.arrange(items_usable, items_edibles, items_extracts, ncol=3)

# 
# 
# 
# 
# usable <- ggplot() +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" &
#                           prod_type=="Usable"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items),
#               method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-06-09" & saledate <= "2016-08-22" &
#                           prod_type=="Usable"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-09-21" & saledate < "2017-01-01" &
#                           prod_type=="Usable"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#1b9e77") +
#   facet_grid(towntype~prod_type, scales="free") +
#   scale_x_date(date_breaks = "3 month", date_labels = "%b") +
#   # add lines to designate summer
#   geom_vline(xintercept= as.numeric(as.Date('2016-05-06')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-06-09')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-08-22')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-09-21')),
#              linetype="dashed", size=0.5, colour="grey") +
#   labs(title="Usable", x= 'Sale Date', y = "")
# 
# edibles <- ggplot() +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" &
#                           prod_type=="Edibles"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items),
#               method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-06-09" & saledate <= "2016-08-22" &
#                           prod_type=="Edibles"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-09-21" & saledate < "2017-01-01" &
#                           prod_type=="Edibles"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#d95f02") +
#   facet_grid(towntype~prod_type, scales="free") +
#   scale_x_date(date_breaks = "3 month", date_labels = "%b") +
#   # add lines to designate summer
#   geom_vline(xintercept= as.numeric(as.Date('2016-05-06')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-06-09')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-08-22')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-09-21')),
#              linetype="dashed", size=0.5, colour="grey") +
#   labs(title="Edibles", x= 'Sale Date', y = "")
# 
# extracts <- ggplot() +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-01-01" & saledate <= "2016-05-06" &
#                           prod_type=="Extracts"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items),
#               method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-06-09" & saledate <= "2016-08-22" &
#                           prod_type=="Extracts"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
#   geom_smooth(data=subset(daily_agg_Pullman_othercollege, saledate >= "2016-09-21" & saledate < "2017-01-01" &
#                           prod_type=="Extracts"),
#               mapping = aes(x=saledate, y=perc_sold*tot_items), 
#               method = 'lm', formula = y~ns(x, df=2), color="#7570b3") +
#   facet_grid(towntype~prod_type, scales="free") +
#   scale_x_date(date_breaks = "3 month", date_labels = "%b") +
#   # add lines to designate summer
#   geom_vline(xintercept= as.numeric(as.Date('2016-05-06')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-06-09')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-08-22')),
#              linetype="dashed", size=0.5, colour="grey")+
#   geom_vline(xintercept= as.numeric(as.Date('2016-09-21')),
#              linetype="dashed", size=0.5, colour="grey") +
#   labs(title="Extracts", x= 'Sale Date', y = "")
# 
# grid.arrange(usable, edibles, extracts, ncol=3)

```




### Extract Use as Percent, by Town Type

```{r towntype_extracts}

inhaltypes <- pullmanUrbanRestofState_inhalants %>%
  dplyr::rename(`Cartridge` = perc_cartridge, `Oil` = perc_oil, `Hash & Kief` = perc_hash_kief,
                `Wax, Shatter, Resin` = perc_wax_shatter_resin, `Uncategorized` = perc_uncategorized) %>%
  tidyr::gather(inhal_group, perc_group, 4:8) %>%
  dplyr::mutate(inhal_group = factor(inhal_group, levels = c("Wax, Shatter, Resin", "Cartridge", "Uncategorized", 
                                                             "Hash & Kief", "Oil"))) %>%
                #towntype = factor(towntype, levels = c("Pullman", "Ellensburg", "Airway Heights", "NCNU", "Urban"))) %>%
  dplyr::rename(`Inhalant Group` = inhal_group)



# breaks for the regressions
ggplot() +
  # different regression lines for spring, summer, and fall
  geom_smooth(data=subset(inhaltypes, saledate >= "2016-01-01" & saledate <="2016-05-06" &
                            towntype!="Airway Heights" & towntype!="Ellensburg"),
              mapping = aes(x=saledate, y=perc_group, color=`Inhalant Group`),
              method = 'lm', formula = y~ns(x, df=3)) + 
  geom_smooth(data=subset(inhaltypes, saledate >= "2016-05-06" & saledate <="2016-08-22" &
                            towntype!="Airway Heights" & towntype!="Ellensburg"),
              mapping = aes(x=saledate, y=perc_group, color=`Inhalant Group`),
              method = 'lm', formula = y~ns(x, df=3)) + 
  geom_smooth(data=subset(inhaltypes, saledate >= "2016-08-22" & saledate <="2016-12-31" &
                            towntype!="Airway Heights" & towntype!="Ellensburg"),
              mapping = aes(x=saledate, y=perc_group, color=`Inhalant Group`),
              method = 'lm', formula = y~ns(x, df=3)) + 
  scale_colour_brewer(palette = "Set2") +
  facet_wrap("towntype", ncol=1, scales="free") +
  scale_y_continuous(labels = scales::percent) +
  # add lines to designate summer
  geom_vline(xintercept= as.numeric(as.Date('2016-5-6')),
             linetype="dashed", size=0.5, colour="dimgrey")+
  geom_vline(xintercept= as.numeric(as.Date('2016-8-22')),
             linetype="dashed", size=0.5, colour="dimgrey") +
  labs(title="Pullman Usage by Inhalant Group Types",
       x="Sale Date",
       y="Percent of Inhalant Sales of Each Group")

```





```{r tables_inhalantuse}
# table summarizing extract use by town type ------

# during spring semester
pullmanUrbanRestofState_inhalants %>%
  dplyr::filter(saledate >= "2016-01-01", saledate < "2016-05-01") %>%
  dplyr::group_by(towntype) %>%
  dplyr::summarise(
    `Cartridge` = round(mean(perc_cartridge*100, na.rm=T),1),
    `Oil` = round(mean(perc_oil*100, na.rm=T),1),
    `Wax, Shatter, Resin` = round(mean(perc_wax_shatter_resin*100, na.rm=T), 1),
    `Hash & Kief` = round(mean(perc_hash_kief*100, na.rm=T),1),
    `Uncategorized` = round(mean(perc_uncategorized*100, na.rm=T),1)
  ) %>%
  kable()

# during summer
pullmanUrbanRestofState_inhalants %>%
  dplyr::filter(saledate >= "2016-06-01", saledate < "2016-08-01") %>%
  dplyr::group_by(towntype) %>%
  dplyr::summarise(
    `Cartridge` = round(mean(perc_cartridge*100, na.rm=T),1),
    `Oil` = round(mean(perc_oil*100, na.rm=T),1),
    `Wax, Shatter, Resin` = round(mean(perc_wax_shatter_resin*100, na.rm=T), 1),
    `Hash, Kief` = round(mean(perc_hash_kief*100, na.rm=T), 1),
    `Uncategorized` = round(mean(perc_uncategorized*100, na.rm=T),1)
  ) %>%
  kable()
```