---
title: "Inventory Holding"
author: "Lauren Renaud"
date: "February, 2017"
output: 
  html_document:
    toc: true
    toc_depth: 4
---
```{r setup, echo=FALSE, include=FALSE, cache.lazy = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(dplyr)
library(readr)
library(ggplot2)
library(gridExtra)
library(knitr)
library(lubridate)
library(RColorBrewer)

# pull in & clean dfs ------
# locatons
locations <- read.csv("../data/Dec2016/cleaned/locations/all_locations.csv", sep=",", header=T)
locations.name.city <- select(locations, retailname = name, licensenum, location_id, city)
retail.loc <- filter(locations, retail==1)
# inventory
inventory <- readr::read_csv("../data/Dec2016/biotrackthc_inventory.csv")
inventory.types <- read.csv("../data/Dec2016/cleaned/inventory_type.csv", sep=",", header=T)
inventory$inv_date <- as.POSIXct(inventory$sessiontime,
                                    origin = "1970-01-01", tz="America/Los_Angeles") # LA = PST
inventory$inv_date <- as.Date(inventory$inv_date)
inventory <- rename(inventory, inventoryid = id)
inventory <- left_join(inventory, inventory.types, by="inventorytype")
inventory.select <- inventory %>%
  #filter(location %in% retail.loc$location_id) %>%
  select(inventoryid, inv_date, inv_type_name, strain, weight, inv_location = location, 
         nv_usableweight = usableweight, productname)

# dispensing
dispensing <- readr::read_csv("../data/Dec2016/biotrackthc_dispensing.csv")
dispensing$saletime <- as.POSIXct(dispensing$sessiontime,
                                   origin = "1970-01-01", tz="America/Los_Angeles") # LA = PST
dispensing$saletime <- as.Date(dispensing$saletime)
dispensing <- left_join(dispensing, inventory.types, by="inventorytype")
dispensing$inv_type_name <- as.factor(dispensing$inv_type_name)
dispensing.select <- dispensing %>%
  select(dispensingid = id, saletime, sale_type = inv_type_name, sale_loc = location, sale_price = price,
         sale_weight = weight, inventoryid, sale_useweight = usableweight)

retail.inventory <- dispensing.select %>%
  dplyr::left_join(inventory.select, by="inventoryid")
retail.inventory$time_in_inv <- as.numeric(difftime(retail.inventory$saletime,
                                                    retail.inventory$inv_date,
                                                    units = "days"))

# % of negative numbers
length(retail.inventory$time_in_inv[retail.inventory$time_in_inv < 0]) / nrow(retail.inventory)

```

# Distribution of Inventory Holding Times

```{r hist}
# histogram of all types
retail.inventory %>%
  filter(time_in_inv > 0) %>%
  ggplot(aes(x=time_in_inv)) +
  geom_histogram(fill="darkgreen") +
  labs(
    title="Time Spent in Stores' Inventory (All)",
    x="Days in Inventory"
  )

# histogram of all types, filtered to <100 days
retail.inventory %>%
  filter(time_in_inv > 0, time_in_inv < 100) %>%
  ggplot(aes(x=time_in_inv)) +
  geom_histogram(fill="darkgreen") +
  labs(
    title="Time Spent in Stores' Inventory (<100 Days)",
    x="Days in Inventory"
  )

# plotting densities by type
retail.inventory %>%
  filter(time_in_inv > 0) %>%
  ggplot(aes(x=time_in_inv)) +
  geom_density(alpha=0.7) +
  facet_wrap("sale_type") +
  #scale_fill_manual(values=plotcolors) +
  #scale_color_manual(values=plotcolors) +
  scale_color_brewer(palette="BuGn") +
  scale_fill_brewer(palette="BuGn") +
  labs(
    title="Density of Time Spent in Stores' Inventory By Type",
    x="Days in Inventory",
    y="Density of Occurance"
  )


# fitlered to <100 days
# plotting densities by type
retail.inventory %>%
  filter(time_in_inv > 0, time_in_inv < 100) %>%
  ggplot(aes(x=time_in_inv)) +
  geom_density(alpha=0.7) +
  facet_wrap("sale_type") +
  scale_fill_manual(values="darkgreen") +
  scale_color_manual(values="darkgreen") +
  #scale_color_brewer(palette="BuGn") +
  #scale_fill_brewer(palette="BuGn") +
  labs(
    title="Density of Time Spent in Stores' Inventory By Type",
    x="Days in Inventory",
    y="Density of Occurance"
  )
```

# Comparing Distributions of Inventory Holding Times

```{r quant_plot}
retail.inventory %>%
  filter(time_in_inv > 0) %>%
  filter(sale_type=="Usable Marijuana" | sale_type=="Solid Marijuana Infused Edible",
         sale_type=="Marijuana Extract for Inhalation" | sale_type=="Liquid Marijuana Infused Edible") %>%
  ggplot(aes(x=time_in_inv)) +
  geom_density(alpha=0.3) +
  labs(title="Inventory Holding Times, Top Types", x="Days in Inventory", y="Density")
  # ggplot(aes(sample = time_in_inv, color=sale_type)) + 
  # stat_qq(distribution="qunif") + 
  # labs(x="Quantiles", y="Days Held in Inventory", color = "Type", 
  #      title = "Distribution of Time in Inventory, Top Types") +
  # scale_color_brewer(palette="BuGn"), color=sale_type, fill=sale_type
  
```

```{r processors_invtime}
# come back to this but look at what did wtih pullman


# recreating retail df for Pullman ------
retail.pullman <- dispensing %>%
  dplyr::filter(location %in% c("457","910","1751","1761","1874")) %>%
  dplyr::left_join(inventory, by="inventoryid") %>%
  dplyr::select(dispensingid, location = location.x, price, usableweight = usableweight.x,
                inv_type_name = inv_type_name.x, retail_invdate = inv_date,
                strain, sale_prodname = productname, weight = weight.x, saletime = monthtime,
                transactionid = transactionid.x, deleted = deleted.x, refunded, inventorytype = inventorytype.x,
                dis_inventoryparentid = inventoryparentid, dis_invid = inventoryid, dis_parentid = parentid) %>%
  left_join(locations.name.city, by=c("location" = "location_id"))

retail.pullman$dis_parentid <- as.numeric(retail.pullman$dis_parentid)

# trying to connect to transfers to get producers
locations <- readr::read_csv("../data/Dec2016/cleaned/locations/all_locations.csv")
loc.types <- readr::read_csv("../data/Dec2016/cleaned/locations/locationtypes.csv")
loc.simp <- locations %>%
  left_join(loc.types, by=c("locationtype" = "loctypeCode")) %>%
  select(location_id, name, typesimp)

transfers <- readr::read_csv("../data/Dec2016/biotrackthc_inventorytransfers.csv")
transfers$inventoryid <- as.numeric(transfers$inventoryid)
transfers$parentid <- as.numeric(transfers$parentid)
transfers.select <- transfers %>%
  select(transferid = id, inventoryid, trans_loc = location, 
         trans_strain = strain, inventorytype, trans_parentid = parentid) %>%
  left_join(inventory.types, by="inventorytype") %>%
  select(-(inventorytype), trans_invtype = inv_type_name) %>%
  left_join(loc.simp, by=c("trans_loc" = "location_id")) %>%
  rename(processor_name = name)

# interesting -- percent of transfers from each type
transfers.select %>%
  group_by(typesimp) %>%
  summarise(perc = n() / nrow(transfers.select))

# there were some (1.8%) of dispensing IDs that came up duplicate on this join
# it appears they have multiple transferIDs that are causing the problem
# need to look into it further, but dropping them for now
dupe.disID <- retail.pullman %>%
  left_join(transfers.select, by=c("dis_invid" = "inventoryid")) %>%
  group_by(dispensingid) %>%
  summarise(count = n()) %>%
  filter(count > 1) %>%
  arrange(desc(count))

# now joining transfers to retail.pullman to get processor names attached to items
retail.pullman <- retail.pullman %>%
  filter(!dispensingid %in% selectingdupes$dispensingid) %>%
  # the inventory id from the dispensing file matches the inventory id in the transfers file
  # maybe we don't even need to go through transfers?
  # checked that yes, trans_loc goes one for oen with processor_name
  left_join(transfers.select, by=c("dis_invid" = "inventoryid")) %>%
  # then the parent id from the dispening file matches the inventory id of the processor's inventory
  left_join(inventory, by=c("dis_parentid" = "inventoryid")) %>%
  select(dispensingid, retail_loc = location.x, saleprice = price, saleuseweight = usableweight.x, sale_invtype = inv_type_name.x,
         sale_strain = strain.x, sale_prodname, saleweight = weight.x, saletime, retail_invdate, transactionid = transactionid.x,
         refunded, dis_invid, retailname, trans_loc, trans_strain, trans_invtype, trans_parentid,
         processor_name, processortype = typesimp, process_strain = strain.y, process_weight = weight.y, process_transctionid = transactionid.y,
         process_productname = productname, processinv_date = inv_date, processor_invtype = inv_type_name.y,
         processor_invid = dis_parentid)

processor.invtime <- retail.pullman %>%
  group_by(dispensingid) %>%
  mutate(process_invtime = retail_invdate - processinv_date) %>%
  select(dispensingid, retail_invdate, processinv_date, process_invtime)


```
